
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author williams
 */
public class JFrameCalcExpressao extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCalcExpressao
     */
    public JFrameCalcExpressao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textExpressao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textExpressao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textExpressaoMouseClicked(evt);
            }
        });

        jLabel1.setText("Digite uma Expressão:");

        buttonCalcular.setText("Calcular");
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });
        buttonCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonCalcularKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textExpressao, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(buttonCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textExpressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(buttonCalcular)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed
        
        String [] valores = textExpressao.getText().split("\\+|\\-|\\*|\\/");
        String op = textExpressao.getText().replaceAll("[0-9]","");
        //String [] op = textExpressao.getText().split("");
        System.out.println(textExpressao.getText());
        // op = operador
        
        float resultado;
        switch (op){
            case"+":
               resultado = Integer.parseInt(valores[0]) + Integer.parseInt(valores[1]);
               JOptionPane.showMessageDialog(this,"o resultado é:"+ resultado, "Resultado Expressão", JOptionPane.INFORMATION_MESSAGE);
               break;
            case"-":
                resultado = Integer.parseInt(valores[0]) - Integer.parseInt(valores[1]);
                JOptionPane.showMessageDialog(this,"o resultado é:"+ resultado, "Resultado Expressão", JOptionPane.INFORMATION_MESSAGE);
                break;
            case"*":
                resultado = Integer.parseInt(valores[0]) * Integer.parseInt(valores[1]);
                JOptionPane.showMessageDialog(this,"o resultado é:"+ resultado, "Resultado Expressão", JOptionPane.INFORMATION_MESSAGE);
                break;
            case"/":
                resultado = Float.parseFloat(valores[0]) / Float.parseFloat(valores[1]);
                JOptionPane.showMessageDialog(this,"o resultado é:"+ resultado, "Resultado Expressão", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(null,"Não utilize espaços, ou digite um operador válido!");
                break;  
        
        }
        
    }//GEN-LAST:event_buttonCalcularActionPerformed

    private void textExpressaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textExpressaoMouseClicked
        // TODO add your handling code here:
        textExpressao.setText("");
    }//GEN-LAST:event_textExpressaoMouseClicked

    private void buttonCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonCalcularKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCalcularKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalcExpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalcExpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalcExpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalcExpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalcExpressao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textExpressao;
    // End of variables declaration//GEN-END:variables
}
